name: Release Java CI

on:
  push:
    tags:
      - "*.*.*.rsp"
      - "*.*.*.rsp-*"
    branches:
      - 'build'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PLAYA_RU_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PLAYA_RU_DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: playaru/keycloak-russian:latest
          build-args: |
            "PLAYA_RU_GITHUB_TOKEN=${{ secrets.PLAYA_RU_GITHUB_TOKEN }}"