name: Release Java CI

on:
  push:
    tags:
      - "*.*.*.rsp"
      - "*.*.*.rsp-*"
    branches:
      - 'build'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: curl
        run: |
          curl -X GET --location "https://maven.pkg.github.com/playa-ru/keycloak-ui/org/keycloak/keycloak-admin-ui/21.1.1.rsp-12/keycloak-admin-ui-21.1.1.rsp-12.jar" -H "Authorization: Bearer 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" -o keycloak-admin-ui-21.1.1.rsp-12.jar
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
          repo-token: ${{ secrets.GITHUB_TOKEN }}